### ISSUE TITLE
Naamgeving van property 'kadastraalOnroerendeZaken' volgt DD1.8 niet

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#31]
De property 'kadastraalOnroerendeZaken' in 'WozObjectHal' volgt DD1.8 niet. Deze zegt:

_Wanneer een relatie-property (niet link of embedded) alleen de identificatie van een gerelateerde resource bevat en geen andere properties, wordt als naam van de property de naam van de resource plus het woord 'Identificatie' gebruikt._

Het schemafragment ziet er als volgt uit:

```
        kadastraalOnroerendeZaken:
          type: array
          description: De kadastraal onroerende zaken die geheel of gedeeltelijk deel uitmaken van het WOZ-object
          items:
            $ref: '#/components/schemas/KadastraalOnroerendeZaak'
```

Terwijl je volgens mij

```
        kadastraalOnroerendeZakenIdentificaties:
          type: array
          description: De kadastraal onroerende zaken die geheel of gedeeltelijk deel uitmaken van het WOZ-object
          items:
            type: string

```
zou verwachten.
