### ISSUE TITLE
onterecht 400 foutmelding op niet-numerieke identificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-WOZ-bevragen#63]
get /wozobjecten/bestaatniet levert nu een 400 foutmelding:
{
    "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "detail": "Parameter 'identificatie' is geen valide wozobject identificatie",
    "instance": "/wozobjecten/bestaatniet",
    "status": 400,
    "code": "paramsValidation"
}

Dit is denk ik niet terecht, want in de specificaties is niet opgegeven waar de identificatie aan moet voldoen, anders dan dat het een string is (en dat is het).
```
      parameters:
        - name: identificatie
          in: path
          description: Unieke identificatie van een WOZ-object
          required: true
          explode: true
          schema:
            type: string
```

Ik had daarom een 404 not found verwacht i.p.v. de 400 fout.

Mogelijk is het wel wenselijk de mogelijke waarden voor identificatie te beperken, bijv. met een pattern. Dat moet dan in de specificaties worden toegevoegd (en dan is de 400 fout wel terecht). Aan de gebruiker moet dan ook in de foutmelding gemeld krijgen waar de identificatie aan moet voldoen om wel een geldige identificatie te kunnen zijn.

Wat zijn de eisen aan de invoer (reguliere expressie, minimale en/of maximale lengte)?

Daarnaast had ik in dit geval (als dat ook in de specificaties is opgenomen) ook invalidParams verwacht, bijvoorbeeld:
    "invalidParams": [
        {
            "name": "nummeraanduidingidentificatie",
            "code": "pattern",
            "reason": "Waarde voldoet niet aan patroon ^[0-9]{12}$."
        }
    ]
